# Generated by Django 3.1.12 on 2025-06-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_news', models.TextField()),
                ('updated_at', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image_news', models.TextField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.TextField()),
                ('content', models.TextField()),
                ('time', models.TextField()),
            ],
            options={
                'db_table': 'notify',
            },
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('date', models.TextField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('volume', models.IntegerField()),
                ('change', models.IntegerField()),
                ('fund_market', models.IntegerField()),
                ('updated_at', models.TextField()),
            ],
            options={
                'db_table': 'stock_detail',
            },
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('company_name', models.TextField()),
                ('industry', models.TextField()),
                ('company_type', models.TextField()),
                ('established_year', models.IntegerField()),
            ],
            options={
                'db_table': 'stock_info',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('role', models.TextField()),
                ('user_token', models.TextField()),
                ('name', models.TextField(null=True)),
                ('phonenumber', models.TextField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
